name: Radtab
favicon: null
layout_spectrum: 0.11419
typography_spectrum: 0.37774
title: Automated Bar Tabs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d3e3d'
    - '#fac04b'
    - '#00a5d5'
    - '#fffffe'
    - '#828281'
  brandStrength: 0.3706593632232398
  lightness: 0.8687570167239755
  saturation: 0.5544131721835583
  rhythmicContrast: 0.3025504460092634
purpose: []
